services:
  - type: web
    name: AfyyaClick-Backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server.app:app"  # change this path if needed
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
