services:
  - type: web
    name: AfyyaClick-Backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"  # or server:app depending on your entry file
    envVars:
      - key: DATABASE_URL
        sync: false
