"""deleted a column

Revision ID: 1a1a6a94c8d6
Revises: 38b21b83eea7
Create Date: 2025-10-01 09:14:33.697862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1a6a94c8d6'
down_revision = '38b21b83eea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
